// norm_model.dart
class NormModel {
  final int stt;
  final String maSanPham;
  final String tenSanPham;
  final String maChiTiet;
  final String tenChiTiet;
  final String suDung;
  final String donViSuDung;
  final String ngayTao;
  final String nguoiTao;
  final String ngayCapNhat;
  final String nguoiCapNhat;

  NormModel({
    required this.stt,
    required this.maSanPham,
    required this.tenSanPham,
    required this.maChiTiet,
    required this.tenChiTiet,
    required this.suDung,
    required this.donViSuDung,
    required this.ngayTao,
    required this.nguoiTao,
    required this.ngayCapNhat,
    required this.nguoiCapNhat,
  });

  factory NormModel.fromJson(Map<String, dynamic> json) {
    return NormModel(
      stt: json['stt'] ?? 0,
      maSanPham: json['maSanPham'] ?? '',
      tenSanPham: json['tenSanPham'] ?? '',
      maChiTiet: json['maChiTiet'] ?? '',
      tenChiTiet: json['tenChiTiet'] ?? '',
      suDung: json['suDung'] ?? '',
      donViSuDung: json['donViSuDung'] ?? '',
      ngayTao: json['ngayTao'] ?? '',
      nguoiTao: json['nguoiTao'] ?? '',
      ngayCapNhat: json['ngayCapNhat'] ?? '',
      nguoiCapNhat: json['nguoiCapNhat'] ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'stt': stt,
      'maSanPham': maSanPham,
      'tenSanPham': tenSanPham,
      'maChiTiet': maChiTiet,
      'tenChiTiet': tenChiTiet,
      'suDung': suDung,
      'donViSuDung': donViSuDung,
      'ngayTao': ngayTao,
      'nguoiTao': nguoiTao,
      'ngayCapNhat': ngayCapNhat,
      'nguoiCapNhat': nguoiCapNhat,
    };
  }

  // 🌟 Mock data
  static List<NormModel> mockData = [
    NormModel(
      stt: 1,
      maSanPham: "SP001",
      tenSanPham: "Bánh răng thép",
      maChiTiet: "CT001",
      tenChiTiet: "Thép tròn 20mm",
      suDung: "2.5",
      donViSuDung: "Kg",
      ngayTao: "2025-10-01",
      nguoiTao: "Admin",
      ngayCapNhat: "2025-10-05",
      nguoiCapNhat: "Hưng",
    ),
    NormModel(
      stt: 2,
      maSanPham: "SP002",
      tenSanPham: "Trục quay",
      maChiTiet: "CT002",
      tenChiTiet: "Thép ống 30mm",
      suDung: "1.2",
      donViSuDung: "Kg",
      ngayTao: "2025-09-20",
      nguoiTao: "Admin",
      ngayCapNhat: "2025-09-30",
      nguoiCapNhat: "Việt",
    ),
    NormModel(
      stt: 3,
      maSanPham: "SP003",
      tenSanPham: "Vỏ hộp số",
      maChiTiet: "CT003",
      tenChiTiet: "Nhôm tấm 5mm",
      suDung: "3.0",
      donViSuDung: "Kg",
      ngayTao: "2025-08-15",
      nguoiTao: "Lan",
      ngayCapNhat: "2025-09-10",
      nguoiCapNhat: "Tuấn",
    ),
    NormModel(
      stt: 4,
      maSanPham: "SP004",
      tenSanPham: "Cánh quạt",
      maChiTiet: "CT004",
      tenChiTiet: "Nhôm tròn 10mm",
      suDung: "0.8",
      donViSuDung: "Kg",
      ngayTao: "2025-07-12",
      nguoiTao: "Hà",
      ngayCapNhat: "2025-08-01",
      nguoiCapNhat: "Minh",
    ),
    NormModel(
      stt: 5,
      maSanPham: "SP005",
      tenSanPham: "Thân máy bơm",
      maChiTiet: "CT005",
      tenChiTiet: "Gang đúc 25kg",
      suDung: "25",
      donViSuDung: "Kg",
      ngayTao: "2025-06-22",
      nguoiTao: "Admin",
      ngayCapNhat: "2025-06-30",
      nguoiCapNhat: "Tùng",
    ),
    NormModel(
      stt: 6,
      maSanPham: "SP006",
      tenSanPham: "Bulong M10",
      maChiTiet: "CT006",
      tenChiTiet: "Thép C45",
      suDung: "0.05",
      donViSuDung: "Kg",
      ngayTao: "2025-05-10",
      nguoiTao: "Duy",
      ngayCapNhat: "2025-06-01",
      nguoiCapNhat: "Việt",
    ),
    NormModel(
      stt: 7,
      maSanPham: "SP007",
      tenSanPham: "Đai ốc M10",
      maChiTiet: "CT007",
      tenChiTiet: "Thép C35",
      suDung: "0.04",
      donViSuDung: "Kg",
      ngayTao: "2025-04-05",
      nguoiTao: "Việt",
      ngayCapNhat: "2025-05-01",
      nguoiCapNhat: "Huy",
    ),
    NormModel(
      stt: 8,
      maSanPham: "SP008",
      tenSanPham: "Bánh xe tải",
      maChiTiet: "CT008",
      tenChiTiet: "Cao su đúc",
      suDung: "6.5",
      donViSuDung: "Kg",
      ngayTao: "2025-03-18",
      nguoiTao: "Linh",
      ngayCapNhat: "2025-03-25",
      nguoiCapNhat: "Bảo",
    ),
    NormModel(
      stt: 9,
      maSanPham: "SP009",
      tenSanPham: "Khung thép",
      maChiTiet: "CT009",
      tenChiTiet: "Thép hộp 20x20",
      suDung: "4.8",
      donViSuDung: "Kg",
      ngayTao: "2025-02-11",
      nguoiTao: "Hùng",
      ngayCapNhat: "2025-02-20",
      nguoiCapNhat: "Việt",
    ),
    NormModel(
      stt: 10,
      maSanPham: "SP010",
      tenSanPham: "Bảng điều khiển",
      maChiTiet: "CT010",
      tenChiTiet: "Nhựa ABS",
      suDung: "1.0",
      donViSuDung: "Kg",
      ngayTao: "2025-01-01",
      nguoiTao: "Việt",
      ngayCapNhat: "2025-01-15",
      nguoiCapNhat: "Dũng",
    ),
    NormModel(
      stt: 11,
      maSanPham: "SP011",
      tenSanPham: "Mô-tơ điện",
      maChiTiet: "CT011",
      tenChiTiet: "Đồng cuộn dây",
      suDung: "2.2",
      donViSuDung: "Kg",
      ngayTao: "2024-12-10",
      nguoiTao: "Tài",
      ngayCapNhat: "2025-01-01",
      nguoiCapNhat: "Lộc",
    ),
    NormModel(
      stt: 12,
      maSanPham: "SP012",
      tenSanPham: "Ống dẫn khí",
      maChiTiet: "CT012",
      tenChiTiet: "Nhựa PVC",
      suDung: "0.9",
      donViSuDung: "Kg",
      ngayTao: "2024-11-01",
      nguoiTao: "Minh",
      ngayCapNhat: "2024-12-01",
      nguoiCapNhat: "Tú",
    ),
    NormModel(
      stt: 13,
      maSanPham: "SP013",
      tenSanPham: "Van nước",
      maChiTiet: "CT013",
      tenChiTiet: "Đồng thau",
      suDung: "1.1",
      donViSuDung: "Kg",
      ngayTao: "2024-10-15",
      nguoiTao: "Trang",
      ngayCapNhat: "2024-11-05",
      nguoiCapNhat: "Việt",
    ),
    NormModel(
      stt: 14,
      maSanPham: "SP014",
      tenSanPham: "Khớp nối",
      maChiTiet: "CT014",
      tenChiTiet: "Thép tròn 12mm",
      suDung: "0.6",
      donViSuDung: "Kg",
      ngayTao: "2024-09-20",
      nguoiTao: "Anh",
      ngayCapNhat: "2024-09-30",
      nguoiCapNhat: "Việt",
    ),
    NormModel(
      stt: 15,
      maSanPham: "SP015",
      tenSanPham: "Lò xo nén",
      maChiTiet: "CT015",
      tenChiTiet: "Thép lò xo",
      suDung: "0.15",
      donViSuDung: "Kg",
      ngayTao: "2024-08-05",
      nguoiTao: "Việt",
      ngayCapNhat: "2024-08-20",
      nguoiCapNhat: "Bình",
    ),
  ];
}
