// product_model.dart
class ProductModel {
  final int stt;
  final String maSanPham;
  final String tenSanPham;
  final String nhomSanPham;
  final double trongLuong;
  final String donViTrongLuong;
  final DateTime ngayTao;
  final String nguoiTao;
  final DateTime ngayCapNhat;
  final String nguoiCapNhat;
  final int soLuongLenhSanXuat;

  ProductModel({
    required this.stt,
    required this.maSanPham,
    required this.tenSanPham,
    required this.nhomSanPham,
    required this.trongLuong,
    required this.donViTrongLuong,
    required this.ngayTao,
    required this.ngayCapNhat,
    required this.nguoiTao,
    required this.nguoiCapNhat,
    required this.soLuongLenhSanXuat,
  });

  /// JSON → Object
  factory ProductModel.fromJson(Map<String, dynamic> json) {
    return ProductModel(
      stt: json['STT'] ?? 0,
      maSanPham: json['MaSanPham'] ?? '',
      tenSanPham: json['TenSanPham'] ?? '',
      nhomSanPham: json['NhomSanPham'] ?? '',
      trongLuong: (json['TrongLuong'] ?? 0).toDouble(),
      donViTrongLuong: json['DonViTrongLuong'] ?? 'kg',
      ngayTao: DateTime.tryParse(json['NgayTao'] ?? '') ?? DateTime.now(),
      nguoiTao: json['NguoiTao'] ?? '',
      ngayCapNhat: DateTime.tryParse(json['NgayTao'] ?? '') ?? DateTime.now(),
      nguoiCapNhat: json['NguoiCapNhat'],
      soLuongLenhSanXuat: json['SoLuongLenhSanXuat'] ?? 0,
    );
  }

  /// Object → JSON
  Map<String, dynamic> toJson() {
    return {
      'STT': stt,
      'MaSanPham': maSanPham,
      'TenSanPham': tenSanPham,
      'NhomSanPham': nhomSanPham,
      'TrongLuong': trongLuong,
      'DonViTrongLuong': donViTrongLuong,
      'NgayTao': ngayTao.toIso8601String(),
      'NguoiTao': nguoiTao,
      'NgayCapNhat': ngayCapNhat?.toIso8601String(),
      'NguoiCapNhat': nguoiCapNhat,
      'SoLuongLenhSanXuat': soLuongLenhSanXuat,
    };
  }

  /// Copy object
  ProductModel copyWith({
    int? stt,
    String? maSanPham,
    String? tenSanPham,
    String? nhomSanPham,
    double? trongLuong,
    String? donViTrongLuong,
    DateTime? ngayTao,
    String? nguoiTao,
    DateTime? ngayCapNhat,
    String? nguoiCapNhat,
    int? soLuongLenhSanXuat,
  }) {
    return ProductModel(
      stt: stt ?? this.stt,
      maSanPham: maSanPham ?? this.maSanPham,
      tenSanPham: tenSanPham ?? this.tenSanPham,
      nhomSanPham: nhomSanPham ?? this.nhomSanPham,
      trongLuong: trongLuong ?? this.trongLuong,
      donViTrongLuong: donViTrongLuong ?? this.donViTrongLuong,
      ngayTao: ngayTao ?? this.ngayTao,
      nguoiTao: nguoiTao ?? this.nguoiTao,
      ngayCapNhat: ngayCapNhat ?? this.ngayCapNhat,
      nguoiCapNhat: nguoiCapNhat ?? this.nguoiCapNhat,
      soLuongLenhSanXuat: soLuongLenhSanXuat ?? this.soLuongLenhSanXuat,
    );
  }

  /// Mock data để test UI hoặc xuất file
  static List<ProductModel> mockData() {
    List<String> creators = ['Việt', 'Tuấn', 'Linh'];

    return [
      ProductModel(
        stt: 1,
        maSanPham: 'SP001',
        tenSanPham: 'Bánh răng thép A1',
        nhomSanPham: 'Cơ khí chính xác',
        trongLuong: 2.5,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 10)),
        nguoiTao: creators[0],
        ngayCapNhat: DateTime.now(),
        nguoiCapNhat: creators[0],
        soLuongLenhSanXuat: 50,
      ),
      ProductModel(
        stt: 2,
        maSanPham: 'SP002',
        tenSanPham: 'Trục xoay B2',
        nhomSanPham: 'Cơ khí chính xác',
        trongLuong: 4.2,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 8)),
        nguoiTao: creators[1],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 1)),
        nguoiCapNhat: creators[1],
        soLuongLenhSanXuat: 30,
      ),
      ProductModel(
        stt: 3,
        maSanPham: 'SP003',
        tenSanPham: 'Vỏ hộp động cơ C3',
        nhomSanPham: 'Thiết bị cơ khí',
        trongLuong: 6.8,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 12)),
        nguoiTao: creators[2],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 2)),
        nguoiCapNhat: creators[2],
        soLuongLenhSanXuat: 40,
      ),
      ProductModel(
        stt: 4,
        maSanPham: 'SP004',
        tenSanPham: 'Tấm nhôm gia công D1',
        nhomSanPham: 'Kim loại nhẹ',
        trongLuong: 1.3,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 7)),
        nguoiTao: creators[0],
        ngayCapNhat: DateTime.now(),
        nguoiCapNhat: creators[0],
        soLuongLenhSanXuat: 70,
      ),
      ProductModel(
        stt: 5,
        maSanPham: 'SP005',
        tenSanPham: 'Khung sắt E2',
        nhomSanPham: 'Vật liệu xây dựng',
        trongLuong: 10.5,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 15)),
        nguoiTao: creators[1],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 3)),
        nguoiCapNhat: creators[1],
        soLuongLenhSanXuat: 25,
      ),
      ProductModel(
        stt: 6,
        maSanPham: 'SP006',
        tenSanPham: 'Ống thép F3',
        nhomSanPham: 'Kim loại nặng',
        trongLuong: 7.6,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 20)),
        nguoiTao: creators[2],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 5)),
        nguoiCapNhat: creators[2],
        soLuongLenhSanXuat: 60,
      ),
      ProductModel(
        stt: 7,
        maSanPham: 'SP007',
        tenSanPham: 'Tay nắm cửa G4',
        nhomSanPham: 'Phụ kiện cơ khí',
        trongLuong: 0.8,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 6)),
        nguoiTao: creators[0],
        ngayCapNhat: DateTime.now(),
        nguoiCapNhat: creators[0],
        soLuongLenhSanXuat: 120,
      ),
      ProductModel(
        stt: 8,
        maSanPham: 'SP008',
        tenSanPham: 'Bulong thép H5',
        nhomSanPham: 'Phụ kiện lắp ráp',
        trongLuong: 0.15,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 3)),
        nguoiTao: creators[1],
        ngayCapNhat: DateTime.now(),
        nguoiCapNhat: creators[1],
        soLuongLenhSanXuat: 200,
      ),
      ProductModel(
        stt: 9,
        maSanPham: 'SP009',
        tenSanPham: 'Đĩa phanh xe tải K9',
        nhomSanPham: 'Cơ khí ô tô',
        trongLuong: 12.3,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 18)),
        nguoiTao: creators[2],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 2)),
        nguoiCapNhat: creators[2],
        soLuongLenhSanXuat: 35,
      ),
      ProductModel(
        stt: 10,
        maSanPham: 'SP010',
        tenSanPham: 'Nắp van áp suất M1',
        nhomSanPham: 'Cơ khí công nghiệp',
        trongLuong: 2.1,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 9)),
        nguoiTao: creators[0],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 1)),
        nguoiCapNhat: creators[0],
        soLuongLenhSanXuat: 90,
      ),

      ProductModel(
        stt: 11,
        maSanPham: 'SP011',
        tenSanPham: 'Bánh đà K1',
        nhomSanPham: 'Cơ khí chính xác',
        trongLuong: 3.4,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 5)),
        nguoiTao: creators[1],
        ngayCapNhat: DateTime.now(),
        nguoiCapNhat: creators[1],
        soLuongLenhSanXuat: 55,
      ),
      ProductModel(
        stt: 12,
        maSanPham: 'SP012',
        tenSanPham: 'Trục cam Z2',
        nhomSanPham: 'Cơ khí chính xác',
        trongLuong: 5.7,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 13)),
        nguoiTao: creators[2],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 4)),
        nguoiCapNhat: creators[2],
        soLuongLenhSanXuat: 65,
      ),
      ProductModel(
        stt: 13,
        maSanPham: 'SP013',
        tenSanPham: 'Thân máy M5',
        nhomSanPham: 'Thiết bị cơ khí',
        trongLuong: 8.1,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 14)),
        nguoiTao: creators[0],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 2)),
        nguoiCapNhat: creators[0],
        soLuongLenhSanXuat: 45,
      ),
      ProductModel(
        stt: 14,
        maSanPham: 'SP014',
        tenSanPham: 'Tấm nhựa kỹ thuật P7',
        nhomSanPham: 'Vật liệu nhựa',
        trongLuong: 1.2,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 6)),
        nguoiTao: creators[1],
        ngayCapNhat: DateTime.now(),
        nguoiCapNhat: creators[1],
        soLuongLenhSanXuat: 80,
      ),
      ProductModel(
        stt: 15,
        maSanPham: 'SP015',
        tenSanPham: 'Khung cửa nhôm S9',
        nhomSanPham: 'Kim loại nhẹ',
        trongLuong: 2.9,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 7)),
        nguoiTao: creators[2],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 1)),
        nguoiCapNhat: creators[2],
        soLuongLenhSanXuat: 95,
      ),
      ProductModel(
        stt: 16,
        maSanPham: 'SP016',
        tenSanPham: 'Ống đồng T2',
        nhomSanPham: 'Kim loại nhẹ',
        trongLuong: 4.5,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 20)),
        nguoiTao: creators[0],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 3)),
        nguoiCapNhat: creators[0],
        soLuongLenhSanXuat: 110,
      ),
      ProductModel(
        stt: 17,
        maSanPham: 'SP017',
        tenSanPham: 'Bánh răng H10',
        nhomSanPham: 'Phụ kiện cơ khí',
        trongLuong: 0.7,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 12)),
        nguoiTao: creators[1],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 1)),
        nguoiCapNhat: creators[1],
        soLuongLenhSanXuat: 140,
      ),
      ProductModel(
        stt: 18,
        maSanPham: 'SP018',
        tenSanPham: 'Đinh vít R3',
        nhomSanPham: 'Phụ kiện lắp ráp',
        trongLuong: 0.12,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 8)),
        nguoiTao: creators[2],
        ngayCapNhat: DateTime.now(),
        nguoiCapNhat: creators[2],
        soLuongLenhSanXuat: 180,
      ),
      ProductModel(
        stt: 19,
        maSanPham: 'SP019',
        tenSanPham: 'Lốc máy P4',
        nhomSanPham: 'Cơ khí ô tô',
        trongLuong: 13.5,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 16)),
        nguoiTao: creators[0],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 5)),
        nguoiCapNhat: creators[0],
        soLuongLenhSanXuat: 33,
      ),
      ProductModel(
        stt: 20,
        maSanPham: 'SP020',
        tenSanPham: 'Van tiết lưu Q8',
        nhomSanPham: 'Cơ khí công nghiệp',
        trongLuong: 2.8,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 11)),
        nguoiTao: creators[1],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 1)),
        nguoiCapNhat: creators[1],
        soLuongLenhSanXuat: 75,
      ),
      ProductModel(
        stt: 21,
        maSanPham: 'SP021',
        tenSanPham: 'Bánh răng M12',
        nhomSanPham: 'Cơ khí chính xác',
        trongLuong: 3.8,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 7)),
        nguoiTao: creators[2],
        ngayCapNhat: DateTime.now(),
        nguoiCapNhat: creators[2],
        soLuongLenhSanXuat: 52,
      ),
      ProductModel(
        stt: 22,
        maSanPham: 'SP022',
        tenSanPham: 'Trục khuỷu N8',
        nhomSanPham: 'Cơ khí chính xác',
        trongLuong: 5.4,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 8)),
        nguoiTao: creators[0],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 3)),
        nguoiCapNhat: creators[0],
        soLuongLenhSanXuat: 60,
      ),
      ProductModel(
        stt: 23,
        maSanPham: 'SP023',
        tenSanPham: 'Thân máy T7',
        nhomSanPham: 'Thiết bị cơ khí',
        trongLuong: 7.7,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 13)),
        nguoiTao: creators[1],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 2)),
        nguoiCapNhat: creators[1],
        soLuongLenhSanXuat: 47,
      ),
      ProductModel(
        stt: 24,
        maSanPham: 'SP024',
        tenSanPham: 'Tấm nhựa kỹ thuật P8',
        nhomSanPham: 'Vật liệu nhựa',
        trongLuong: 1.1,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 6)),
        nguoiTao: creators[2],
        ngayCapNhat: DateTime.now(),
        nguoiCapNhat: creators[2],
        soLuongLenhSanXuat: 82,
      ),
      ProductModel(
        stt: 25,
        maSanPham: 'SP025',
        tenSanPham: 'Khung cửa nhôm S10',
        nhomSanPham: 'Kim loại nhẹ',
        trongLuong: 3.0,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 7)),
        nguoiTao: creators[0],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 1)),
        nguoiCapNhat: creators[0],
        soLuongLenhSanXuat: 100,
      ),
      ProductModel(
        stt: 26,
        maSanPham: 'SP026',
        tenSanPham: 'Ống đồng T3',
        nhomSanPham: 'Kim loại nhẹ',
        trongLuong: 4.7,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 19)),
        nguoiTao: creators[1],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 4)),
        nguoiCapNhat: creators[1],
        soLuongLenhSanXuat: 115,
      ),
      ProductModel(
        stt: 27,
        maSanPham: 'SP027',
        tenSanPham: 'Bánh răng H11',
        nhomSanPham: 'Phụ kiện cơ khí',
        trongLuong: 0.6,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 11)),
        nguoiTao: creators[2],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 1)),
        nguoiCapNhat: creators[2],
        soLuongLenhSanXuat: 135,
      ),
      ProductModel(
        stt: 28,
        maSanPham: 'SP028',
        tenSanPham: 'Đinh vít R4',
        nhomSanPham: 'Phụ kiện lắp ráp',
        trongLuong: 0.14,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 8)),
        nguoiTao: creators[0],
        ngayCapNhat: DateTime.now(),
        nguoiCapNhat: creators[0],
        soLuongLenhSanXuat: 185,
      ),
      ProductModel(
        stt: 29,
        maSanPham: 'SP029',
        tenSanPham: 'Lốc máy P5',
        nhomSanPham: 'Cơ khí ô tô',
        trongLuong: 14.2,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 15)),
        nguoiTao: creators[1],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 4)),
        nguoiCapNhat: creators[1],
        soLuongLenhSanXuat: 40,
      ),
      ProductModel(
        stt: 30,
        maSanPham: 'SP030',
        tenSanPham: 'Van tiết lưu Q9',
        nhomSanPham: 'Cơ khí công nghiệp',
        trongLuong: 3.0,
        donViTrongLuong: 'kg',
        ngayTao: DateTime.now().subtract(const Duration(days: 10)),
        nguoiTao: creators[2],
        ngayCapNhat: DateTime.now().subtract(const Duration(days: 2)),
        nguoiCapNhat: creators[2],
        soLuongLenhSanXuat: 80,
      ),
    ];
  }
}
