class BaoGiaModel {
  final String maBaoGia;
  final String maKhachHang;
  final String tenSanPham;
  final DateTime ngayGui;
  final DateTime ngayGiaoYC;
  final DateTime ngayXacNhanKH;
  final int soLuong;
  final double donGia;
  final double tongTien;
  final String donViTienTe;
  final String trangThai;
  final String? ghiChu;
  final DateTime ngayTao;
  final String nguoiTao;
  final DateTime? ngayCapNhat;
  final String? nguoiCapNhat;

  BaoGiaModel({
    required this.maBaoGia,
    required this.maKhachHang,
    required this.tenSanPham,
    required this.ngayGui,
    required this.ngayGiaoYC,
    required this.ngayXacNhanKH,
    required this.soLuong,
    required this.donGia,
    required this.tongTien,
    required this.donViTienTe,
    required this.trangThai,
    this.ghiChu,
    required this.ngayTao,
    required this.nguoiTao,
    this.ngayCapNhat,
    this.nguoiCapNhat,
  });

  // Nếu cần, bạn có thể thêm factory từ JSON hoặc toJson ở đây
}

final List<BaoGiaModel> mockBaoGiaData = [
  BaoGiaModel(
    maBaoGia: 'BG001',
    maKhachHang: 'KH001',
    tenSanPham: 'Trục cơ khí A',
    ngayGui: DateTime.parse('2025-11-01'),
    ngayGiaoYC: DateTime.parse('2025-11-05'),
    ngayXacNhanKH: DateTime.parse('2025-11-03'),
    soLuong: 100,
    donGia: 15000,
    tongTien: 100 * 15000,
    donViTienTe: 'VND',
    trangThai: 'Đã xác nhận',
    ghiChu: 'Giao hàng nhanh',
    ngayTao: DateTime.parse('2025-10-31'),
    nguoiTao: 'Nguyễn Văn A',
    ngayCapNhat: DateTime.parse('2025-11-02'),
    nguoiCapNhat: 'Trần Thị B',
  ),
  BaoGiaModel(
    maBaoGia: 'BG002',
    maKhachHang: 'KH002',
    tenSanPham: 'Vòng bi SKF',
    ngayGui: DateTime.parse('2025-11-02'),
    ngayGiaoYC: DateTime.parse('2025-11-10'),
    ngayXacNhanKH: DateTime.parse('2025-11-04'),
    soLuong: 50,
    donGia: 25000,
    tongTien: 50 * 25000,
    donViTienTe: 'VND',
    trangThai: 'Chờ xác nhận',
    ghiChu: null,
    ngayTao: DateTime.parse('2025-11-01'),
    nguoiTao: 'Lê Văn C',
    ngayCapNhat: null,
    nguoiCapNhat: null,
  ),
  BaoGiaModel(
    maBaoGia: 'BG003',
    maKhachHang: 'KH003',
    tenSanPham: 'Bánh răng truyền động',
    ngayGui: DateTime.parse('2025-10-15'),
    ngayGiaoYC: DateTime.parse('2025-10-20'),
    ngayXacNhanKH: DateTime.parse('2025-10-18'),
    soLuong: 200,
    donGia: 10000,
    tongTien: 200 * 10000,
    donViTienTe: 'VND',
    trangThai: 'Đã đặt hàng',
    ghiChu: 'Ưu tiên khách VIP',
    ngayTao: DateTime.parse('2025-10-14'),
    nguoiTao: 'Phạm Thị D',
    ngayCapNhat: DateTime.parse('2025-10-19'),
    nguoiCapNhat: 'Phan Văn E',
  ),
  BaoGiaModel(
    maBaoGia: 'BG004',
    maKhachHang: 'KH004',
    tenSanPham: 'Piston xi lanh',
    ngayGui: DateTime.parse('2025-09-30'),
    ngayGiaoYC: DateTime.parse('2025-10-05'),
    ngayXacNhanKH: DateTime.parse('2025-10-02'),
    soLuong: 10,
    donGia: 500000,
    tongTien: 10 * 500000,
    donViTienTe: 'VND',
    trangThai: 'Đã hủy',
    ghiChu: 'Khách hàng huỷ do thay đổi kế hoạch',
    ngayTao: DateTime.parse('2025-09-29'),
    nguoiTao: 'Trần Văn F',
    ngayCapNhat: DateTime.parse('2025-10-03'),
    nguoiCapNhat: 'Trương Thị G',
  ),
  BaoGiaModel(
    maBaoGia: 'BG005',
    maKhachHang: 'KH005',
    tenSanPham: 'Van điều khiển',
    ngayGui: DateTime.parse('2025-11-07'),
    ngayGiaoYC: DateTime.parse('2025-11-15'),
    ngayXacNhanKH: DateTime.parse('2025-11-10'),
    soLuong: 80,
    donGia: 30000,
    tongTien: 80 * 30000,
    donViTienTe: 'VND',
    trangThai: 'Đang chờ',
    ghiChu: 'Chờ xác nhận lại từ khách hàng',
    ngayTao: DateTime.parse('2025-11-06'),
    nguoiTao: 'Lý Thị H',
    ngayCapNhat: null,
    nguoiCapNhat: null,
  ),
  BaoGiaModel(
    maBaoGia: 'BG006',
    maKhachHang: 'KH006',
    tenSanPham: 'Khớp nối trục',
    ngayGui: DateTime.parse('2025-11-05'),
    ngayGiaoYC: DateTime.parse('2025-11-12'),
    ngayXacNhanKH: DateTime.parse('2025-11-09'),
    soLuong: 150,
    donGia: 12000,
    tongTien: 150 * 12000,
    donViTienTe: 'VND',
    trangThai: 'Đang xử lý',
    ghiChu: 'Đang chuẩn bị hàng',
    ngayTao: DateTime.parse('2025-11-04'),
    nguoiTao: 'Vũ Văn I',
    ngayCapNhat: DateTime.parse('2025-11-08'),
    nguoiCapNhat: 'Đinh Thị K',
  ),
  BaoGiaModel(
    maBaoGia: 'BG007',
    maKhachHang: 'KH007',
    tenSanPham: 'Trục vít me',
    ngayGui: DateTime.parse('2025-10-25'),
    ngayGiaoYC: DateTime.parse('2025-10-30'),
    ngayXacNhanKH: DateTime.parse('2025-10-28'),
    soLuong: 300,
    donGia: 8000,
    tongTien: 300 * 8000,
    donViTienTe: 'VND',
    trangThai: 'Hoàn thành',
    ghiChu: 'Giao hàng đúng hạn',
    ngayTao: DateTime.parse('2025-10-24'),
    nguoiTao: 'Nguyễn Thị L',
    ngayCapNhat: DateTime.parse('2025-10-29'),
    nguoiCapNhat: 'Phạm Văn M',
  ),
  BaoGiaModel(
    maBaoGia: 'BG008',
    maKhachHang: 'KH008',
    tenSanPham: 'Đai ốc bulong',
    ngayGui: DateTime.parse('2025-11-09'),
    ngayGiaoYC: DateTime.parse('2025-11-20'),
    ngayXacNhanKH: DateTime.parse('2025-11-15'),
    soLuong: 20,
    donGia: 45000,
    tongTien: 20 * 45000,
    donViTienTe: 'VND',
    trangThai: 'Bị trả lại',
    ghiChu: 'Sản phẩm lỗi, khách trả lại',
    ngayTao: DateTime.parse('2025-11-08'),
    nguoiTao: 'Trần Văn N',
    ngayCapNhat: DateTime.parse('2025-11-16'),
    nguoiCapNhat: 'Lê Thị O',
  ),
  BaoGiaModel(
    maBaoGia: 'BG009',
    maKhachHang: 'KH009',
    tenSanPham: 'Thanh dẫn hướng',
    ngayGui: DateTime.parse('2025-11-10'),
    ngayGiaoYC: DateTime.parse('2025-11-18'),
    ngayXacNhanKH: DateTime.parse('2025-11-12'),
    soLuong: 60,
    donGia: 22000,
    tongTien: 60 * 22000,
    donViTienTe: 'VND',
    trangThai: 'Đã đặt hàng',
    ghiChu: 'Giao hàng chậm trễ do thời tiết',
    ngayTao: DateTime.parse('2025-11-09'),
    nguoiTao: 'Phạm Văn P',
    ngayCapNhat: DateTime.parse('2025-11-13'),
    nguoiCapNhat: 'Ngô Thị Q',
  ),
  BaoGiaModel(
    maBaoGia: 'BG010',
    maKhachHang: 'KH010',
    tenSanPham: 'Xi lanh thuỷ lực',
    ngayGui: DateTime.parse('2025-11-11'),
    ngayGiaoYC: DateTime.parse('2025-11-21'),
    ngayXacNhanKH: DateTime.parse('2025-11-15'),
    soLuong: 90,
    donGia: 18000,
    tongTien: 90 * 18000,
    donViTienTe: 'VND',
    trangThai: 'Chờ xác nhận',
    ghiChu: null,
    ngayTao: DateTime.parse('2025-11-10'),
    nguoiTao: 'Vũ Thị R',
    ngayCapNhat: null,
    nguoiCapNhat: null,
  ),
  BaoGiaModel(
    maBaoGia: 'BG011',
    maKhachHang: 'KH01',
    tenSanPham: 'Xi lanh cao cấp',
    ngayGui: DateTime.parse('2025-11-11'),
    ngayGiaoYC: DateTime.parse('2025-11-21'),
    ngayXacNhanKH: DateTime.parse('2025-11-15'),
    soLuong: 90,
    donGia: 18000,
    tongTien: 90 * 18000,
    donViTienTe: 'VND',
    trangThai: 'Chờ xác nhận',
    ghiChu: null,
    ngayTao: DateTime.parse('2025-11-10'),
    nguoiTao: 'Vũ Thị R',
    ngayCapNhat: null,
    nguoiCapNhat: null,
  ),
  BaoGiaModel(
    maBaoGia: 'BG012',
    maKhachHang: 'KH011',
    tenSanPham: 'Bơm thủy lực cao áp',
    ngayGui: DateTime.parse('2025-11-12'),
    ngayGiaoYC: DateTime.parse('2025-11-22'),
    ngayXacNhanKH: DateTime.parse('2025-11-16'),
    soLuong: 40,
    donGia: 350000,
    tongTien: 40 * 350000,
    donViTienTe: 'VND',
    trangThai: 'Đang xử lý',
    ghiChu: 'Cần kiểm tra chất lượng trước khi giao',
    ngayTao: DateTime.parse('2025-11-11'),
    nguoiTao: 'Trần Văn S',
    ngayCapNhat: DateTime.parse('2025-11-14'),
    nguoiCapNhat: 'Nguyễn Thị T',
  ),
  BaoGiaModel(
    maBaoGia: 'BG013',
    maKhachHang: 'KH012',
    tenSanPham: 'Motor điện 3 pha',
    ngayGui: DateTime.parse('2025-11-13'),
    ngayGiaoYC: DateTime.parse('2025-11-25'),
    ngayXacNhanKH: DateTime.parse('2025-11-18'),
    soLuong: 70,
    donGia: 220000,
    tongTien: 70 * 220000,
    donViTienTe: 'VND',
    trangThai: 'Chờ xác nhận',
    ghiChu: 'Khách hàng muốn giao vào đầu tháng sau',
    ngayTao: DateTime.parse('2025-11-12'),
    nguoiTao: 'Lê Văn U',
    ngayCapNhat: null,
    nguoiCapNhat: null,
  ),
  BaoGiaModel(
    maBaoGia: 'BG014',
    maKhachHang: 'KH013',
    tenSanPham: 'Van một chiều',
    ngayGui: DateTime.parse('2025-11-05'),
    ngayGiaoYC: DateTime.parse('2025-11-15'),
    ngayXacNhanKH: DateTime.parse('2025-11-10'),
    soLuong: 120,
    donGia: 50000,
    tongTien: 120 * 50000,
    donViTienTe: 'VND',
    trangThai: 'Đã xác nhận',
    ghiChu: 'Giao hàng đúng hẹn',
    ngayTao: DateTime.parse('2025-11-04'),
    nguoiTao: 'Phạm Văn V',
    ngayCapNhat: DateTime.parse('2025-11-09'),
    nguoiCapNhat: 'Phan Thị W',
  ),
  BaoGiaModel(
    maBaoGia: 'BG015',
    maKhachHang: 'KH014',
    tenSanPham: 'Bộ lọc dầu',
    ngayGui: DateTime.parse('2025-11-07'),
    ngayGiaoYC: DateTime.parse('2025-11-17'),
    ngayXacNhanKH: DateTime.parse('2025-11-12'),
    soLuong: 90,
    donGia: 75000,
    tongTien: 90 * 75000,
    donViTienTe: 'VND',
    trangThai: 'Đã đặt hàng',
    ghiChu: 'Sản phẩm phải đạt tiêu chuẩn ISO',
    ngayTao: DateTime.parse('2025-11-06'),
    nguoiTao: 'Đỗ Văn X',
    ngayCapNhat: DateTime.parse('2025-11-11'),
    nguoiCapNhat: 'Lê Thị Y',
  ),
  BaoGiaModel(
    maBaoGia: 'BG016',
    maKhachHang: 'KH015',
    tenSanPham: 'Bộ truyền động dây curoa',
    ngayGui: DateTime.parse('2025-11-08'),
    ngayGiaoYC: DateTime.parse('2025-11-18'),
    ngayXacNhanKH: DateTime.parse('2025-11-13'),
    soLuong: 55,
    donGia: 98000,
    tongTien: 55 * 98000,
    donViTienTe: 'VND',
    trangThai: 'Đang chờ',
    ghiChu: 'Chờ khách hàng phản hồi về số lượng',
    ngayTao: DateTime.parse('2025-11-07'),
    nguoiTao: 'Nguyễn Văn Z',
    ngayCapNhat: null,
    nguoiCapNhat: null,
  ),
  BaoGiaModel(
    maBaoGia: 'BG017',
    maKhachHang: 'KH016',
    tenSanPham: 'Đầu nối nhanh khí nén',
    ngayGui: DateTime.parse('2025-11-09'),
    ngayGiaoYC: DateTime.parse('2025-11-19'),
    ngayXacNhanKH: DateTime.parse('2025-11-14'),
    soLuong: 130,
    donGia: 12000,
    tongTien: 130 * 12000,
    donViTienTe: 'VND',
    trangThai: 'Đã hủy',
    ghiChu: 'Khách hàng huỷ do thay đổi thiết kế',
    ngayTao: DateTime.parse('2025-11-08'),
    nguoiTao: 'Trần Thị AA',
    ngayCapNhat: DateTime.parse('2025-11-15'),
    nguoiCapNhat: 'Phạm Văn BB',
  ),
  BaoGiaModel(
    maBaoGia: 'BG018',
    maKhachHang: 'KH017',
    tenSanPham: 'Ống dẫn dầu chịu nhiệt',
    ngayGui: DateTime.parse('2025-11-10'),
    ngayGiaoYC: DateTime.parse('2025-11-20'),
    ngayXacNhanKH: DateTime.parse('2025-11-15'),
    soLuong: 75,
    donGia: 68000,
    tongTien: 75 * 68000,
    donViTienTe: 'VND',
    trangThai: 'Hoàn thành',
    ghiChu: 'Đã nghiệm thu và thanh toán',
    ngayTao: DateTime.parse('2025-11-09'),
    nguoiTao: 'Lê Văn CC',
    ngayCapNhat: DateTime.parse('2025-11-16'),
    nguoiCapNhat: 'Nguyễn Thị DD',
  ),
];
